/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieticketingbookingsystem;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanzkie
 */
public class Print extends javax.swing.JFrame {

	/**
	 * Creates new form Print
	 */
	public Print() {
		initComponents();
	
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DISPLAY = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();
        print = new javax.swing.JButton();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 478));
        setSize(new java.awt.Dimension(820, 478));
        getContentPane().setLayout(null);

        DISPLAY.setText("DISPLAY");
        DISPLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAYActionPerformed(evt);
            }
        });
        getContentPane().add(DISPLAY);
        DISPLAY.setBounds(580, 370, 90, 60);

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(DisplayTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 100, 390, 340);

        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(680, 370, 130, 60);

        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize);
        minimize.setBounds(710, 0, 50, 50);

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(770, 0, 50, 50);

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieticketingbookingsystem/homeimages/background8.png"))); // NOI18N
        getContentPane().add(header);
        header.setBounds(0, 0, 820, 48);

        background.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieticketingbookingsystem/homeimages/receiptdisplay.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(824, 430));
        background.setMinimumSize(new java.awt.Dimension(824, 430));
        getContentPane().add(background);
        background.setBounds(0, 50, 820, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       PrinterJob job = PrinterJob.getPrinterJob();
      job.setJobName("Print Data");
      
      job.setPrintable(new Printable(){
		  
        public int print (Graphics pg, PageFormat pf, int pageNum){
                pf.setOrientation(PageFormat.LANDSCAPE);
           
		    
				if (pageNum>0){
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());

            
            return Printable.PAGE_EXISTS;
            
        }
});
        boolean ok = job.printDialog();
        if(ok){
            try{
				boolean complete = DisplayTable.print();
                job.print();
                
			  
				JOptionPane.showMessageDialog(rootPane, "Print Started!");
			} catch(PrinterException ex) {
				JOptionPane.showMessageDialog(rootPane, "Print Error!");
			}
        }
                                         
    }//GEN-LAST:event_printActionPerformed

    private void DISPLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAYActionPerformed
       try {
			String filePath = "C:\\Users\\vanzkie\\Documents\\NetBeansProjects\\movieticketingbookingsystem\\src\\movieticketingbookingsystem\\forprint\\print.txt";
			File file = new File(filePath);
			BufferedReader br = new BufferedReader(new FileReader(file));
			String firstLine = br.readLine().trim();
			String[] columnsName = firstLine.split(",");
			DefaultTableModel model = (DefaultTableModel) DisplayTable.getModel();
			model.setColumnIdentifiers(columnsName);
			Object[] tabLelines = br.lines().toArray();
			for (int i = 0; i < tabLelines.length; i++) {
				String line = tabLelines[i].toString().trim();
				String[] dataRow = line.split("/");
				model.addRow(dataRow);
			}
			JOptionPane.showMessageDialog(rootPane, "Success!");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(rootPane, "fail!");

		
    }                                           
    }//GEN-LAST:event_DISPLAYActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Print().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DISPLAY;
    private javax.swing.JTable DisplayTable;
    private javax.swing.JLabel background;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
